Namarina2/Controllers/ReportController.cs
using Namarina2.DAL;
using Namarina2.Filters;
using Namarina2.Models;
using Novacode;
using Spire.Doc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Namarina2.Controllers
{
    //[InitializeSimpleMembership]
    public class ReportController : Controller
    {
        //
        // GET: /Report/

        private NamarinaDbContext db = new NamarinaDbContext();


        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DailyReport()
        {
            return View();
        }
        public ActionResult WeeklyReport()
        {
            return View();
        }
        public ActionResult MonthlyReport()
        {
            return View();
        }

        [Authorize]
        public JsonResult GetReport(DateTime datefrom, DateTime dateto, string branch)
        {
            if (branch == "PUSAT")
            {
                return Json(new
                {
                    reportData = (from d in db.InvoicesPusat// join s in db.Students on d.StudentID equals s.StudentID
                                  where d.PaymentDate >= datefrom && d.PaymentDate <= dateto //&& s.Branch.ToUpper() == branch.ToUpper()
                                  select new
                     {
                         DateTimeReport = d.PaymentDate,
                         StudentCode = d.StudentCode,
                         StudentName = d.StudentName,
                         Enrollments = d.Enrollments,
                         Period = d.PaymentPeriodString,
                         Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price
                     }).ToList()
                },
                            JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new
                {
                    reportData = (from d in db.InvoicesKebayoran// join s in db.Students on d.StudentID equals s.StudentID
                                  where d.PaymentDate >= datefrom && d.PaymentDate <= dateto //&& s.Branch.ToUpper() == branch.ToUpper()
                                  select new
                                  {
                                      DateTimeReport = d.PaymentDate,
                                      StudentCode = d.StudentCode,
                                      StudentName = d.StudentName,
                                      Enrollments = d.Enrollments,
                                      Period = d.PaymentPeriodString,
                                      Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price
                                  }).ToList()
                },
                          JsonRequestBehavior.AllowGet);
            }
        }

        public FileResult GetDailyReport(string branch, DateTime reportdate, string expenses)
        {
            var now = DateTime.Now;
            var admin = User.Identity.Name;
            var listExpenses = new JavaScriptSerializer().Deserialize<List<Expense>>(expenses);
            var reportData = new List<dynamic>();
            if (branch == "Pusat")
            {
                reportData.Add((from d in db.InvoicesPusat// join s in db.Students on d.StudentID equals s.StudentID
                              where d.PaymentDate.Value.Day == reportdate.Day && d.PaymentDate.Value.Month == reportdate.Month && d.PaymentDate.Value.Year == reportdate.Year
                              && d.Branch.ToUpper() == branch.ToUpper()
                              //&& d.AdminUserName == admin
                              select new
                               {
                                   DateTimeReport = d.PaymentDate,
                                   StudentCode = d.StudentCode,
                                   StudentName = d.StudentName,
                                   Enrollments = d.Enrollments,
                                   Period = d.PaymentPeriodString,
                                   Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price,
                                   Penalty = d.Penalty
                               }).ToList());
            }
            else
            {
                reportData.Add((from d in db.InvoicesKebayoran// join s in db.Students on d.StudentID equals s.StudentID
                           where d.PaymentDate.Value.Day == reportdate.Day && d.PaymentDate.Value.Month == reportdate.Month && d.PaymentDate.Value.Year == reportdate.Year
                           && d.Branch.ToUpper() == branch.ToUpper()
                           //&& d.AdminUserName == admin
                           select new
                           {
                               DateTimeReport = d.PaymentDate,
                               StudentCode = d.StudentCode,
                               StudentName = d.StudentName,
                               Enrollments = d.Enrollments,
                               Period = d.PaymentPeriodString,
                               Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price,
                               Penalty = d.Penalty
                           }).ToList());
            }
            var registrationInvoice = from d in db.RegistrationInvoices
                                      where d.PaymentDate.Value.Day == reportdate.Day
                                      && d.PaymentDate.Value.Month == reportdate.Month
                                      && d.PaymentDate.Value.Year == reportdate.Year  
                                      && d.Branch.ToUpper() == branch.ToUpper()
                                      //&& d.AdminUserName == admin
                                      select d;
            decimal totalPenalty = 0;
            decimal totalPayment = 0;
            decimal totalRegistration = 0;

            try
            {
                 totalPenalty = reportData.Sum(m => m.Penalty);
                 totalPayment = reportData.Sum(m => m.Price);

                 totalRegistration = registrationInvoice.Sum(m => m.Price) ?? 0;
            } catch(Exception ex) { }
            var grandTotal = totalPenalty + totalPayment + totalRegistration;
           
            var docx = DocX.Load(Server.MapPath("~/Content/laporanharian.docx"));
            //docx.ReplaceText("[[BULAN]]", new DateTime(2000, month, 1).ToString("MMMM", new CultureInfo("id-ID")).ToUpper());
            docx.ReplaceText("[[TOTALDENDA]]",totalPenalty.ToString("N2", new CultureInfo("id-ID")));
            docx.ReplaceText("[[TOTALPEMBAYARAN]]", totalPayment.ToString("N2", new CultureInfo("id-ID")));
            docx.ReplaceText("[[TOTALPENDAFTARAN]]", totalRegistration.ToString("N2", new CultureInfo("id-ID")));
            docx.ReplaceText("[[GRANDTOTAL]]", grandTotal.ToString("N2", new CultureInfo("id-ID")));
            docx.ReplaceText("[[CABANG]]", branch.ToUpper());
            docx.ReplaceText("[[TANGGAL]]", reportdate.ToString("dd MMM yyyy", new CultureInfo("id-ID")));
            docx.ReplaceText("[[DESKRIPSI]]", (string.Join("\r\n", listExpenses.Select(s => s.name).ToArray())));
            docx.ReplaceText("[[HARGA]]", (string.Join("\r\n", listExpenses.Select(s => "Rp. " + s.price).ToArray())));
            docx.ReplaceText("[[ADMIN]]", User.Identity.Name);
            var memoryStream = new MemoryStream();
            docx.SaveAs(memoryStream);
            // File(memoryStream.ToArray(), "application/vnd.openxmlformats-officedocument.wordprocessingml.document", "laporanharian.doc");

            Document document = new Document();
            document.LoadFromStream(memoryStream, FileFormat.Docx);
            var pdfStream = new MemoryStream();
            document.SaveToStream(pdfStream, FileFormat.PDF);
            return File(pdfStream.ToArray(), "application/pdf", "laporanharian.pdf");

        }

        public FileResult GetWeeklyReport(string branch, DateTime reportdate, string expenses)
        {
            var now = DateTime.Now;
            var admin = User.Identity.Name;
            var listExpenses = new JavaScriptSerializer().Deserialize<List<Expense>>(expenses);
            var reportData = new List<dynamic>();
            if (branch == "Pusat")
            {
                reportData.Add((from d in db.InvoicesPusat// join s in db.Students on d.StudentID equals s.StudentID
                                where d.PaymentDate.Value.Day == reportdate.Day && d.PaymentDate.Value.Month == reportdate.Month && d.PaymentDate.Value.Year == reportdate.Year
                                && d.Branch.ToUpper() == branch.ToUpper()
                                //&& d.AdminUserName == admin
                                select new
                                {
                                    DateTimeReport = d.PaymentDate,
                                    StudentCode = d.StudentCode,
                                    StudentName = d.StudentName,
                                    Enrollments = d.Enrollments,
                                    Period = d.PaymentPeriodString,
                                    Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price,
                                    Penalty = d.Penalty
                                }).ToList());
            }
            else
            {
                reportData.Add((from d in db.InvoicesKebayoran// join s in db.Students on d.StudentID equals s.StudentID
                                where d.PaymentDate.Value.Day == reportdate.Day && d.PaymentDate.Value.Month == reportdate.Month && d.PaymentDate.Value.Year == reportdate.Year
                                && d.Branch.ToUpper() == branch.ToUpper()
                                //&& d.AdminUserName == admin
                                select new
                                {

Namarina2/Views/Report/DailyReport.cshtml
@{
    ViewBag.Title = "DailyReport";
}

<h2>Daily Report</h2>
<form>
    <div class="display-label">
        Tanggal
    </div>
    <div class="display-field">
        @Html.TextBox("ReportDate", string.Empty, new { @class = "datepicker", @placeholder = "dd/mm/yyyy" })
    </div>

    <div class="display-label">
        Cabang
    </div>
    <div class="display-field">
        @Html.DropDownList("Branch", new List<SelectListItem> { 
        new SelectListItem { Text = "Pusat", Value = "Pusat"},
        new SelectListItem { Text = "Kebayoran", Value = "Kebayoran"}    
})
    </div>
    @*<div class="display-label">
        Pengeluaran
    </div>
    <div class="display-field">
        <table data-bind='visible: expenses().length > 0'>
            <thead>
                <tr>
                    <th>Deskripsi</th>
                    <th>Jumlah</th>
                    <th />
                </tr>
            </thead>
            <tbody data-bind='foreach: expenses'>
                <tr>
                    <td>
                        <input class='required' data-bind='value: name, uniqueName: true' /></td>
                    <td>
                        <input class='required number' data-bind='value: price, uniqueName: true' /></td>
                    <td><a href='#' data-bind='click: $root.removeExpense'>Delete</a></td>
                </tr>
            </tbody>
        </table>

        <button data-bind='click: addExpense'>Tambah Pengeluaran</button>
           <button data-bind='enable: expenses().length > 0' type='submit'>Submit</button>
    </div>*@
    <div class="display-label">
        <br />
        <br />
        <p>
            <input id="generatedailyreport" class="button" type="button" value="Buat Laporan Harian" />
        </p>
</form>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {

            $('.datepicker').kendoDatePicker({
                culture: "id-ID",
                format: "dd/MM/yyyy",
                value: new Date()
            });

            $("#generatedailyreport").click(function (e) {
               location.href = "@Url.Action("GetDailyReport", "Report")" + "/?reportdate=" + kendo.toString($("#ReportDate").data("kendoDatePicker").value(), "yyyy-MM-dd") + "&branch=" + $("#Branch").val() + "&expenses=" + viewModel.save();
            });
        });

            var ExpenseModel = function (expenses) {
                var self = this;
                self.expenses = ko.observableArray(expenses);

                self.addExpense = function () {
                    self.expenses.push({
                        name: "",
                        price: ""
                    });
                };

                self.removeExpense = function (expense) {
                    self.expenses.remove(expense);
                };

                self.save = function (form) {
                    return ko.utils.stringifyJson(self.expenses);
                    // To actually transmit to server as a regular form post, write this: ko.utils.postJson($("form")[0], self.gifts);
                };
            };

            var viewModel = new ExpenseModel([]);
            ko.applyBindings(viewModel);

            // Activate jQuery Validation
            //$("form").validate({ submitHandler: viewModel.save });
    </script>
}

Namarina2/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Payment Report</h2>
<br /><br />
<fieldset>
<div style="clear: both">
<div class="editor-label">
    Dari
</div>
<div class="editor-field">
    @Html.TextBox("From", string.Empty, new { @class = "datepicker", @placeholder = "dd/mm/yyyy" })
</div>

<div class="editor-label">
    Sampai
</div>
<div class="editor-field">
    @Html.TextBox("To", string.Empty, new { @class = "datepicker", @placeholder = "dd/mm/yyyy" })
</div>

<div class="editor-label">
    Cabang
</div>
<div class="editor-field">
    @Html.DropDownList("Branch", new List<SelectListItem> {
        new SelectListItem { Value = "PUSAT", Text = "Pusat" },
        new SelectListItem { Value = "KEBAYORAN", Text = "Kebayoran" }
    })
    </div>
    </div>
</fieldset>
<br />
<p>
    <input id="generatereport" class="button" type="button" value="Buat Laporan" />
</p>


<br />

<div id="report" style="display: none">
    <table id="grid-report">
    </table>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        var datasource = {};
        $(document).ready(function () {
          
            $('.datepicker').kendoDatePicker({
                culture: "id-ID",
                format: "dd/MM/yyyy"
            });

            $("#generatedailyreport").click(function (e) {
                location.href = "@Url.Action("GetDailyReport", "Report")";

            });

            $("#generatereport").click(function (e) {
                var data = {};
                data.datefrom = kendo.toString($("#From").data("kendoDatePicker").value(), "yyyy-MM-dd");
                data.dateto = kendo.toString($("#To").data("kendoDatePicker").value(), "yyyy-MM-dd");
                data.branch =  $("#Branch").val();

                $.ajax({
                    type: "GET",
                    cache: false,
                    url: "@Url.Action("GetReport", "Report")",
                    data : data,
                success: function (data) {
                    datasource = data;
                    InitGrid();
                }
                 });
            });
        });

        function InitGrid() {
            $("#report").empty();
            $("#report").append("<table id=\"grid-report\"></table>");
            $("#grid-report").kendoGrid({
                dataSource: {
                    data:  datasource.reportData,
                    schema: {
                        model: {
                            fields: {
                                DateTimeReport: { type: "date" },
                                StudentCode: { type: "string" },
                                StudentName: { type: "string" },
                                Enrollments: { type: "string" },
                                Period: { type: "string" },
                                Price: { type: "string" }
                            }
                        }
                    },
                    pageSize: 10
                },
                dataBound: function (e) {
                    $('#ajax-loader').hide();
                    $('#report').show();
                },
                pageable: true,
                filterable: true,
                columns: [                           
                            {
                                field: "DateTimeReport",
                                title: "Tanggal Bayar",
                                headerAttributes: {
                                    "class": "center",
                                },
                                template: '#= kendo.toString(DateTimeReport,"d MMM yyyy") #',
                                width: 100,
                            },
                            {
                                field: "StudentCode",
                                title: "Kode Siswa",
                                headerAttributes: {
                                    "class": "center",
                                },
                                width: 200
                            },
                            {
                                field: "StudentName",
                                title: "Nama",
                                headerAttributes: {
                                    "class": "center",
                                }
                            },
                            {
                                field: "Enrollments",
                                title: "Kelas",
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }
                            },
                            {
                                field: "Period",
                                title: "Periode",
                                headerAttributes: {
                                    "class": "center",
                                }
                            },
                            {
                                field: "Price",
                                title: "Harga",                               
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }
                            }
                ]

            });
        }
    </script>
}

Namarina2/Views/Report/MonthlyReport.cshtml
@{
    ViewBag.Title = "MonthlyReport";
}
<h2>Monthly Report</h2>
<form>
    <div class="display-label">
        Bulan
    </div>
    <div class="display-field">
        <select>
            <option>Januari</option>
            <option>Februari</option>
            <option>Maret</option>
            <option>April</option>
            <option>Mei</option>
            <option>Juni</option>
            <option>Juli</option>
            <option>Agustus</option>
            <option>September</option>
            <option>Oktober</option>
            <option>November</option>
            <option>Desenber</option>
        </select>
    </div>
    <div class="display-label">
        Tanggal
    </div>
    <div class="display-field">
        <select>
            <option>2014</option>
            <option>2015</option>
            <option>2016</option>
            <option>2017</option>
        </select>
    </div>
    <div class="display-label">
        Cabang
    </div>
    <div class="display-field">
        @Html.DropDownList("Branch", new List<SelectListItem> {
        new SelectListItem { Text = "Pusat", Value = "Pusat"},
        new SelectListItem { Text = "Kebayoran", Value = "Kebayoran"}
})
    </div>
    @*<div class="display-label">
            Pengeluaran
        </div>
        <div class="display-field">
            <table data-bind='visible: expenses().length > 0'>
                <thead>
                    <tr>
                        <th>Deskripsi</th>
                        <th>Jumlah</th>
                        <th />
                    </tr>
                </thead>
                <tbody data-bind='foreach: expenses'>
                    <tr>
                        <td>
                            <input class='required' data-bind='value: name, uniqueName: true' /></td>
                        <td>
                            <input class='required number' data-bind='value: price, uniqueName: true' /></td>
                        <td><a href='#' data-bind='click: $root.removeExpense'>Delete</a></td>
                    </tr>
                </tbody>
            </table>

            <button data-bind='click: addExpense'>Tambah Pengeluaran</button>
               <button data-bind='enable: expenses().length > 0' type='submit'>Submit</button>
        </div>*@
    <div class="display-label">
        <br />
        <br />
        <p>
            <input id="generatedailyreport" class="button" type="button" value="Buat Laporan Bulanan" />
        </p>
</form>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {

            $('.datepicker').kendoDatePicker({
                culture: "id-ID",
                format: "dd/MM/yyyy",
                value: new Date()
            });

            $("#generatedailyreport").click(function (e) {
               location.href = "@Url.Action("GetMonthlyReport", "Report")" + "/?reportdate=" + kendo.toString($("#ReportDate").data("kendoDatePicker").value(), "yyyy-MM-dd") + "&branch=" + $("#Branch").val() + "&expenses=" + viewModel.save();
            });
        });

            var ExpenseModel = function (expenses) {
                var self = this;
                self.expenses = ko.observableArray(expenses);

                self.addExpense = function () {
                    self.expenses.push({
                        name: "",
                        price: ""
                    });
                };

                self.removeExpense = function (expense) {
                    self.expenses.remove(expense);
                };

                self.save = function (form) {
                    return ko.utils.stringifyJson(self.expenses);
                    // To actually transmit to server as a regular form post, write this: ko.utils.postJson($("form")[0], self.gifts);
                };
            };

            var viewModel = new ExpenseModel([]);
            ko.applyBindings(viewModel);

            // Activate jQuery Validation
            //$("form").validate({ submitHandler: viewModel.save });
    </script>
}

Namarina2/Views/Report/WeeklyReport.cshtml
@{
    ViewBag.Title = "WeeklyReport";
}
<h2>Weekly Report</h2>
<form>
    <div class="editor-label">
        Dari
    </div>
    <div class="editor-field">
        @Html.TextBox("From", string.Empty, new { @class = "datepicker", @placeholder = "dd/mm/yyyy" })
    </div>
    <div class="editor-label">
        Sampai
    </div>
    <div class="editor-field">
        @Html.TextBox("To", string.Empty, new { @class = "datepicker", @placeholder = "dd/mm/yyyy" })
    </div>
    <div class="display-label">
        Cabang
    </div>
    <div class="display-field">
        @Html.DropDownList("Branch", new List<SelectListItem> {
        new SelectListItem { Text = "Pusat", Value = "Pusat"},
        new SelectListItem { Text = "Kebayoran", Value = "Kebayoran"}
})
    </div>
    @*<div class="display-label">
            Pengeluaran
        </div>
        <div class="display-field">
            <table data-bind='visible: expenses().length > 0'>
                <thead>
                    <tr>
                        <th>Deskripsi</th>
                        <th>Jumlah</th>
                        <th />
                    </tr>
                </thead>
                <tbody data-bind='foreach: expenses'>
                    <tr>
                        <td>
                            <input class='required' data-bind='value: name, uniqueName: true' /></td>
                        <td>
                            <input class='required number' data-bind='value: price, uniqueName: true' /></td>
                        <td><a href='#' data-bind='click: $root.removeExpense'>Delete</a></td>
                    </tr>
                </tbody>
            </table>

            <button data-bind='click: addExpense'>Tambah Pengeluaran</button>
               <button data-bind='enable: expenses().length > 0' type='submit'>Submit</button>
        </div>*@
    <div class="display-label">
        <br />
        <br />
        <p>
            <input id="generatedailyreport" class="button" type="button" value="Buat Laporan Mingguan" />
        </p>
</form>
</div>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {

            $('.datepicker').kendoDatePicker({
                culture: "id-ID",
                format: "dd/MM/yyyy",
                value: new Date()
            });

            $("#generatedailyreport").click(function (e) {
               location.href = "@Url.Action("GetWeeklyReport", "Report")" + "/?reportdate=" + kendo.toString($("#ReportDate").data("kendoDatePicker").value(), "yyyy-MM-dd") + "&branch=" + $("#Branch").val() + "&expenses=" + viewModel.save();
            });
        });

            var ExpenseModel = function (expenses) {
                var self = this;
                self.expenses = ko.observableArray(expenses);

                self.addExpense = function () {
                    self.expenses.push({
                        name: "",
                        price: ""
                    });
                };

                self.removeExpense = function (expense) {
                    self.expenses.remove(expense);
                };

                self.save = function (form) {
                    return ko.utils.stringifyJson(self.expenses);
                    // To actually transmit to server as a regular form post, write this: ko.utils.postJson($("form")[0], self.gifts);
                };
            };

            var viewModel = new ExpenseModel([]);
            ko.applyBindings(viewModel);

            // Activate jQuery Validation
            //$("form").validate({ submitHandler: viewModel.save });
    </script>
}