Namarina2/Models/OneTimePayment.cs
using Foolproof;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Namarina2.Models
{
    public class OneTimePayment
    {        
        [DisplayName("Nama")]
        [MaxLength(250)]
        [Required]
        public string Name { get; set; }

        [Required]
        public int ClassId { get; set; }     
   
        public int? FixedPrice { get; set; }
        [RequiredIfNotEmpty("FixedPrice")]
        public string ReasonFixedPrice { get; set; }

        public static List<SelectListItem> GetClassList()
        {
            var db = new Namarina2.DAL.NamarinaDbContext();
            var classes = db.Classes;
            var result = new List<SelectListItem>();
            foreach (var c in classes)
            {
                result.Add(new SelectListItem { Value = c.ClassID.ToString(), Text = c.ClassCode + " - " + c.Name });
            }
            return result;
        }
    }   
}

Namarina2/Models/Payment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Namarina2.Models
{
    public class Payment
    {
        [Key]
        public int PaymentID { get; set; }
        public DateTime? PaymentDate { get; set; }
        public DateTime PaymentPeriod { get; set; }
        public virtual int StudentID { get; set; }
        public virtual Student Student { get; set; }
        [MaxLength(10)]
        public string StudentCode { get; set; }
        [MaxLength(250)]
        public string StudentName { get; set; }
        [MaxLength(500)]
        public string Enrollments { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Penalty { get; set; }
        public decimal? Price { get; set; }
        public decimal? FixedPrice { get; set; }
        public string ReasonFixedPrice { get; set; }
        public bool IsNotPayPenalty { get; set; }
        public bool Paid { get; set; }
        public int? InvoiceID { get; set; }
    }

    public class InvoicesPusat
    {
        [Key]
        public int InvoiceID { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentPeriodString { get; set; }
        public int StudentID { get; set; }
        [MaxLength(10)]
        public string StudentCode { get; set; }
        [MaxLength(250)]
        public string StudentName { get; set; }
        [MaxLength(500)]
        public string Enrollments { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Penalty { get; set; }
        public decimal? Price { get; set; }
        public decimal? FixedPrice { get; set; }
        public string ReasonFixedPrice { get; set; }
        public bool IsNotPayPenalty { get; set; }
        public bool Paid { get; set; }
        [MaxLength(250)]
        public string AdminUserName { get; set; }
        [MaxLength(50)]
        public string Branch { get; set; }
    }
    public class InvoicesKebayoran
    {
        [Key]
        public int InvoiceID { get; set; }
        public DateTime? PaymentDate { get; set; }
        public string PaymentPeriodString { get; set; }
        public int StudentID { get; set; }
        [MaxLength(10)]
        public string StudentCode { get; set; }
        [MaxLength(250)]
        public string StudentName { get; set; }
        [MaxLength(500)]
        public string Enrollments { get; set; }
        public decimal? Discount { get; set; }
        public decimal? Penalty { get; set; }
        public decimal? Price { get; set; }
        public decimal? FixedPrice { get; set; }
        public string ReasonFixedPrice { get; set; }
        public bool IsNotPayPenalty { get; set; }
        public bool Paid { get; set; }
        [MaxLength(250)]
        public string AdminUserName { get; set; }
        [MaxLength(50)]
        public string Branch { get; set; }
    }

    public class RegistrationInvoice
    {
        public int RegistrationInvoiceID { get; set; }
        public DateTime? PaymentDate { get; set; }
        public int StudentID { get; set; }
        [MaxLength(10)]
        public string StudentCode { get; set; }
        [MaxLength(250)]
        public string StudentName { get; set; }
        [MaxLength(500)]
        public string Enrollments { get; set; }
        public decimal? Price { get; set; }
        public decimal? FixedPrice { get; set; }
        public string ReasonFixedPrice { get; set; }
        public int Status { get; set; }
        [MaxLength(250)]
        public string AdminUserName { get; set; }
        [MaxLength(50)]
        public string Branch { get; set; }
        public DateTime? PaymentPeriod { get; set; }
    }

}

Namarina2/Controllers/PaymentController.cs
using Kendo.DynamicLinq;
using Namarina2.DAL;
using Namarina2.Filters;
using Namarina2.Models;
using Namarina2.ViewModels;
using Novacode;
using System;
using System.Collections.Generic;
using System.Data;
//using System.Data.SqlClient;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Spire.Doc;
using Dapper;

namespace Namarina2.Controllers
{
    //[InitializeSimpleMembership]
    public class PaymentController : Controller
    {
        private NamarinaDbContext db = new NamarinaDbContext();

        //
        // GET: /Payment/
        [Authorize]
        public ActionResult Index()
        {
            var model = new PaymentFormModel();
            return View(model);
        }
        //public ActionResult UpdatePaidStatus()
        //{

        //    var db2 = new NamarinaEntities();
        //    var students = (from d in db2.Payments select d.StudentCode).Distinct();
        //    foreach (var s in students)
        //    {
        //        //cari status paid terakhir
        //        var query = (from d in db2.Payments where d.Paid == true && d.StudentCode == s orderby d.PaymentPeriod select d.PaymentPeriod).FirstOrDefault();
        //        if (query != null)
        //        {

        //            //update semua payment period sebelum query
        //            var paymentPeriods = from d in db2.Payments where d.Paid == false && d.StudentCode == s && d.PaymentPeriod < query select d;
        //            foreach (var p in paymentPeriods)
        //            {
        //                p.Paid = true;
        //            }
        //        }
        //    }


        //    db2.SaveChanges();


        //    return View("Success");
        //}

        //public ActionResult UpdatePayments()
        //{

        //    var db2 = new NamarinaEntities();
        //    var query = db2.pembayarans.ToList().Skip(100).Take(100);
        //    foreach (var q in query)
        //    {
        //        var classes = new List<string>();
        //        decimal price = 0;
        //        if (!string.IsNullOrEmpty(q.NDA)) //nda
        //        {
        //            var ndaPriceRow = (from d in db2.NDAPrices where d.Name == q.NDA select d).Single();
        //            if (q.IsTeacher == "yes") //disc 50%
        //            {
        //                price = ndaPriceRow.DiscPrice50.Value;
        //            }
        //            else if (q.IsPassHigherGrade == "yes") //disc 10%
        //            {
        //                price = ndaPriceRow.DiscPrice10.Value;
        //            }
        //            else
        //            {
        //                price = ndaPriceRow.Price;
        //            }
        //            //cek special class
        //            classes = new List<string>();
        //            if (!string.IsNullOrEmpty(q.Kelas1) && q.Kelas1.Contains("SC")) classes.Add(q.Kelas1);
        //            if (!string.IsNullOrEmpty(q.Kelas2) && q.Kelas2.Contains("SC")) classes.Add(q.Kelas2);
        //            if (!string.IsNullOrEmpty(q.Kelas3) && q.Kelas3.Contains("SC")) classes.Add(q.Kelas3);
        //            if (!string.IsNullOrEmpty(q.Kelas4) && q.Kelas4.Contains("SC")) classes.Add(q.Kelas4);
        //            if (!string.IsNullOrEmpty(q.Kelas5) && q.Kelas5.Contains("SC")) classes.Add(q.Kelas5);
        //            decimal totalPrice = 0;
        //            foreach (var c in classes)
        //            {
        //                var classPrice = (from d in db2.Classes where d.ClassCode == c select d.Price).SingleOrDefault();
        //                if (classPrice != null)
        //                {
        //                    totalPrice += classPrice;
        //                }
        //            }
        //            price += totalPrice;

        //            if (q.IsNYD == "yes") //disc 25%
        //            {
        //                price = price - (price * 25 / 100);
        //                price = Math.Ceiling((decimal)price / 5000) * 5000; //buletin 10000 ke atas
        //            }
        //        }
        //        else
        //        { //ketengan
        //            classes = new List<string>();
        //            if (!string.IsNullOrEmpty(q.Kelas1)) classes.Add(q.Kelas1);
        //            if (!string.IsNullOrEmpty(q.Kelas2)) classes.Add(q.Kelas2);
        //            if (!string.IsNullOrEmpty(q.Kelas3)) classes.Add(q.Kelas3);
        //            if (!string.IsNullOrEmpty(q.Kelas4)) classes.Add(q.Kelas4);
        //            if (!string.IsNullOrEmpty(q.Kelas5)) classes.Add(q.Kelas5);
        //            decimal totalPrice = 0;
        //            var isBFAP = false;
        //            var isBFAK = false;
        //            foreach (var c in classes)
        //            {
        //                if (c == "BFA/P") isBFAP = true;
        //                if (c == "BFA/K") isBFAK = true;

        //                var classPrice = (from d in db2.Classes where d.ClassCode == c select d.Price).SingleOrDefault();
        //                if (classPrice != null)
        //                {
        //                    totalPrice += classPrice;
        //                }
        //            }

        //            price = totalPrice;

        //            //cek bfa 2x
        //            if (isBFAP && isBFAK)
        //            {
        //                price = price - 150000;
        //            }
        //        }

        //        //kurangi tebet
        //        var kelasTebet = new List<string>();
        //        classes = new List<string>();
        //        if (!string.IsNullOrEmpty(q.Kelas1)) classes.Add(q.Kelas1);
        //        if (!string.IsNullOrEmpty(q.Kelas2)) classes.Add(q.Kelas2);
        //        if (!string.IsNullOrEmpty(q.Kelas3)) classes.Add(q.Kelas3);
        //        if (!string.IsNullOrEmpty(q.Kelas4)) classes.Add(q.Kelas4);
        //        if (!string.IsNullOrEmpty(q.Kelas5)) classes.Add(q.Kelas5);
        //        foreach (var c in classes)
        //        {
        //            if (c.Contains("/T"))
        //            {
        //                kelasTebet.Add(c);
        //            }
        //        }
        //        decimal totalHargaTebet = 0;
        //        foreach (var k in kelasTebet)
        //        {
        //            var hargaKelasTebet = 200000;// (from d in db2.Classes where d.ClassCode == k select d.Price).Single();
        //            totalHargaTebet += hargaKelasTebet;
        //        }
        //        price = price - totalHargaTebet;
        //        var query2 = (from d in db2.Payments where d.StudentCode == q.Kode select d).ToList();
        //        foreach (var q2 in query2)
        //        {
        //            q2.Price = price;
        //        }

        //        db2.SaveChanges();
        //    }
        //    return View("Success");
        //}
               
        [Authorize]
        public ActionResult GetHaventPaidStudents()
        {

            //var studentPayments = db.Database.SqlQuery<StudentPayment>("select p.StudentId, p.StudentCode, StudentName,substring((select ', ' + right(Convert(varchar,PaymentPeriod,106),8)"
            //                 + "from payments where PaymentPeriod <= getdate() and StudentId = p.StudentId and paid = 0 for xml path ('')), 3,9999) as PaymentPeriods"
            //                 + "from payments p join students s on p.StudentID = s.StudentId"
            //                 + "where s.Status = 1 and p.PaymentPeriod <= getdate()"
            //                 + "group by p.StudentID, p.StudentCode, StudentName OFFSET " + skip + " ROWS FETCH NEXT " + take + "ROWS ONLY", new object[] { }).ToList();

            var studentPayments = db.Database.SqlQuery<StudentPayment>("[dbo].ViewStudentPayment", new object[] { }).ToList();
            var studentData = from m in studentPayments //join s in db.Students on m.StudentId equals s.StudentID
                              //              where s.Status == "1"
                              select new
                {
                    StudentId = m.StudentId,
                    StudentCode = m.StudentCode,
                    Name = m.StudentName,
                    PaymentPeriods = m.PaymentPeriods,
                    Status = (m.PaymentPeriods != null) ? "<span class=\"blabel warning\">belum bayar</span>" : "<span class=\"blabel success\">lunas</span>"
                };
            return Json(new
            {
                studentData = studentData
            }, JsonRequestBehavior.AllowGet);
        }

        public FileResult GetNotPaid(DateTime pertanggal, string branch)
        {
            //reportData = (from d in db.Invoices// join s in db.Students on d.StudentID equals s.StudentID
            //                 where d.PaymentDate >= datefrom && d.PaymentDate <= dateto //&& s.Branch.ToUpper() == branch.ToUpper()
            //                 select new 
            //    {
            //        DateTimeReport = d.PaymentDate,
            //        StudentCode = d.StudentCode,
            //        StudentName = d.StudentName,
            //        Enrollments = d.Enrollments,
            //        Period = d.PaymentPeriodString,
            //        Price = (d.FixedPrice != null) ? d.FixedPrice : d.Price
            //    }).ToList();
            var studentPayments = db.Database.SqlQuery<StudentPayment>("[dbo].ViewStudentPayment", new object[] { }).ToList();
            var studentData = from m in studentPayments
                              join s in db.Students on m.StudentId equals s.StudentID
                              //where s.Status == "1"
                              where m.PaymentPeriods != null
                              select new
            {
                StudentId = m.StudentId,

Namarina2/Views/Report/Payment/OneTimePayment.cshtml
@{
    ViewBag.Title = "OneTimePayment";
}
@model Namarina2.Models.OneTimePayment
<h2>Bayar Per Kali Datang</h2>


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
         <div class="editor-label">
            Nama
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

          <div class="editor-label">
           Kelas
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(m=>m.ClassId, Namarina2.Models.OneTimePayment.GetClassList())
            @Html.ValidationMessageFor(model => model.ClassId)
        </div>

        <div class="editor-label">
            Harga Pembetulan
        </div>
        <div class="editor-field">
       @Html.TextBoxFor(model => model.FixedPrice)
        </div>

        <div class="editor-label">
           Alasan Harga Pembetulan
        </div>
        <div class="editor-field">
            @Html.TextBoxFor(model => model.ReasonFixedPrice)
            @Html.ValidationMessageFor(model => model.ReasonFixedPrice)
        </div>
       
        <br /><br />
        <br /><br /><br /><br /><br /><br />
         <h2>Harga : Rp. <span id="hargakelas"></span></h2>
        <p>
            <input type="submit" value="Bayar" />
        </p>
    </fieldset>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/MvcFoolproofJQueryValidation.min.js"></script>
        <script src="~/Scripts/mvcfoolproof.unobtrusive.min.js"></script>
    <script>
        function getHarga(classId) {
            $.post("@Url.Action("GetClassPrice")", { classId: classId }, function (result) {
                $("#hargakelas").html(result);
            });
        }
        $(document).ready(function () {
            $("#ClassId").select2();
            getHarga($("#ClassId").val());
            $("#ClassId").change(function (e) {
                getHarga($("#ClassId").val());
            });
            $("#FixedPrice").change(function (e) {
                $("#hargakelas").html($("#FixedPrice").val());
            });
        });
    </script>
}

Namarina2/Views/Report/Payment/PaymentPage.cshtml
@model Namarina2.ViewModels.PaymentDetails
@{
    ViewBag.Title = "Halaman Pembayaran";
}

<h2>Halaman Pembayaran</h2>

<div id="details-container">
    <span id="adminfield">Tanggal Bayar : @DateTime.Now.ToShortDateString()</span>
    @Html.HiddenFor(m => m.PaymentDate, new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.Day))
    @Html.HiddenFor(m => m.StudentId)
    <h3>@Model.StudentCode</h3>
    <h3>@Model.StudentName</h3>
    <div id="monthlypaymentstring">
        <table id="gridMonthlyPayment"></table>
    </div>
    <button >Bayar bulan depan</button>

    <h3>TotalPrice : <span id="totalprice"></span></h3>
    <h3>Penalty : <span id="totalpenalty"></span></h3>
    <h2>Grand Total : <span id="grandtotalprice"></span></h2> <br />  
    
    <h3>Jenis Pembayaran</h3>
    <input type="radio" name="jenispembayaran" value="tunai" checked /> Tunai
    <input type="radio" name="jenispembayaran" value="edcbca" /> EDC BCA
    <input type="radio" name="jenispembayaran" value="edcmandiri" />EDC Mandiri
    <input type="radio" name="jenispembayaran" value="transferbca" />Transfer BCA
    <input type="radio" name="jenispembayaran" value="transfermandiri" />Transfer Mandiri
    <br/><br/>
    @if (User.IsInRole("manajer"))
    {        
        <input type="checkbox" id="isfixprice" /> @Html.Raw("Pembetulan Harga") <input id="fixedprice" /> <br/>
        @Html.Raw("Alasan Pembetulan") <input id="reason"/>
    }

</div>
<br />
<button class="button" id="konfirmasibayar" >Konfirmasi Bayar</button>
<br /><br>
@section scripts
{
<script>
    var dataSourceMonthlyPayment = {};
    var totalPenalty = 0;
    var grandTotalPrice = 0;
    var listPaidDates = []
    $(document).ready(function () {
        $.ajax({
            type: "GET",
            cache: false,
            url: "@Url.Action("GetPaymentDetail", "Payment")" + "/?studentId=" + $("#StudentId").val(),
            success: function (data) {
                dataSourceMonthlyPayment = data.studentData.MonthlyPayments;
                $("#totalpenalty").html(data.studentData.TotalPenalty);
                $("#totalprice").html(data.studentData.TotalPrice);
                $("#grandtotalprice").html(data.studentData.GrandTotalPrice);
                InitGridMonthlyPayment();
            }
        });


        $(document).on('click', '#konfirmasibayar', function () {          
            var listPaidDates = [];
            $("input[id^='cb-']").each(function (e) {
                if (this.checked) {
                    listPaidDates.push(studentdata.MonthlyPayments[e].PaymentPeriod);
                }
            });
            location.href = "@Url.Action("Pay", "Payment")" + "/?studentId=" + $("#StudentId").val() + "&fixedPrice=" + $("#fixedprice").val() + "&reason=" + $("#reason").val() + "&isnotpaypenalty=false" + "&penalty=" + parseInt($("#totalpenalty").html()) + "&paiddates=" + JSON.stringify(listPaidDates) + "&paymentDate=" + $("#PaymentDate").val();
        });
    });



    function InitGridMonthlyPayment()
    {
        $("#gridMonthlyPayment").kendoGrid({
            dataSource: {
                data: dataSourceMonthlyPayment,
               
                pageSize: 10
            },
            dataBound: function (e) {

            },
            pageable: true,
            filterable: true,
            columns: [
                 { template: '<input type="checkbox" checked class="chkbx" />', width: 110 },
                            {
                                field: "PaymentPeriod",
                                title: "Periode",
                                type: 'date',
                                template: '#= kendo.toString(PaymentPeriod, "MMM yyyy") #',
                                width: 100
                            },
                            {
                                field: "PaymentPeriod",
                                title: "Periode",
                                type: 'date',
                                template: '#= kendo.toString(PaymentPeriod, "MMM yyyy") #',
                                width: 100
                            },
                            {
                                field: "Classes",
                                title: "Kelas",
                                width: 200
                            },
                            {
                                field: "Price",
                                title: "Biaya",
                                width: 130,
                                attributes: {
                                    "class": "right"
                                }
                            },
                            {
                                field: "Penalty",
                                title: "Penalty",
                                width: 130,
                                attributes: {
                                    "class": "right"
                                }
                            }
            ]
        });
    }

</script>
}

Namarina2/Views/Report/Payment/PaymentSuccess.cshtml
@{
    ViewBag.Title = "PaymentSuccess";
}

<h2>Pembayaran Berhasil</h2>
<br /><br />
@Html.ActionLink("Print", "Print", new { @studentId = ViewBag.StudentId }, new { @class="button" })       