Namarina2/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Namarina2.Models;
using Namarina2.DAL;
using Namarina2.ViewModels;
using Namarina2.Filters;

namespace Namarina2.Controllers
{
    [InitializeSimpleMembership]
    public class ClassController : Controller
    {
        private NamarinaDbContext db = new NamarinaDbContext();

        //
        // GET: /Class/
        [Authorize]
        public ActionResult Index()
        {
            return View(db.Classes.ToList());
        }

        //
        // GET: /Class/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Class myclass = db.Classes.Find(id);
            var studentInClass = (from e in myclass.Enrollments
                                  join s in db.Students on e.StudentID equals s.StudentID
                                  where e.ClassID == id && s.Status == "1"
                                  select s).ToList();

            if (myclass == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
            {
                ViewBag.StudentInClass = studentInClass;
                return PartialView(myclass);
            }

            return View(myclass);
        }
       

        //
        // GET: /Class/Create
        [Authorize(Roles="manajer")]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Class/Create

        [HttpPost]
        [Authorize(Roles = "manajer")]
        public ActionResult Create(Class myclass)
        {
            if (ModelState.IsValid)
            {
                db.Classes.Add(myclass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(myclass);
        }

        //
        // GET: /Class/Edit/5
        [Authorize(Roles = "manajer")]
        public ActionResult Edit(int id = 0)
        {
            Class myclass = db.Classes.Find(id);
            if (myclass == null)
            {
                return HttpNotFound();
            }
            return View(myclass);
        }

        //
        // POST: /Class/Edit/5

        [HttpPost]
        [Authorize(Roles = "manajer")]
        public ActionResult Edit(Class myclass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(myclass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(myclass);
        }

        //
        // GET: /Class/Delete/5
        [Authorize(Roles = "manajer")]
        public ActionResult Delete(int id = 0)
        {
            Class myclass = db.Classes.Find(id);
            if (myclass == null)
            {
                return HttpNotFound();
            }
            return View(myclass);
        }

        //
        // POST: /Class/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "manajer")]
        public ActionResult DeleteConfirmed(int id)
        {
            Class myclass = db.Classes.Find(id);
            db.Classes.Remove(myclass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        [Authorize]
        public JsonResult GetClasses(string branch)
        {
            var result = db.Classes.Where(o=>o.Branch.ToUpper() == branch.ToUpper()).Select(m => new
                {
                    ClassID = m.ClassID,
                    ClassCode = m.ClassCode,
                    Name = m.Name,
                    StudentCount = (from e in m.Enrollments join s in db.Students on e.StudentID equals s.StudentID
                                   where e.ClassID == m.ClassID && s.Status == "1"
                                   select s.StudentID).Count()//m.Enrollments.Where(n=>n.ClassID == m.ClassID).Count()
                }).ToList();
            return Json(new
            {
                classData = result
            },
                        JsonRequestBehavior.AllowGet);
        }
    }
}

Namarina2/Views/Class/Create.cshtml
@model Namarina2.Models.Class

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Class</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.ClassCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClassCode)
            @Html.ValidationMessageFor(model => model.ClassCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Type)
        </div>
        <div class="editor-field">
               @Html.DropDownListFor(model => model.Type, new List<SelectListItem>()
                                                        {new SelectListItem() {Selected = true, Text="Ballet", Value="Ballet" },
                                                         new SelectListItem() {Text="Jazz", Value="Jazz"},
                                                         new SelectListItem() {Text="Fitness", Value="Fitness"}},
                                                         new { @style = "height:25px;width:150px" })
        
            @Html.ValidationMessageFor(model => model.Type)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.SubType)
        </div>
        <div class="editor-field">
              @Html.DropDownListFor(model => model.SubType, new List<SelectListItem>()
                                                        {new SelectListItem() {Selected = true, Text="Ballet", Value="Ballet" },
                                                         new SelectListItem() {Text="Fitness", Value="Fitness"},
                                                         new SelectListItem() {Text="Graded", Value="Graded"},
                                                         new SelectListItem() {Text="Hiphop", Value="Hiphop"},
                                                         new SelectListItem() {Text="Special", Value="Special"},
                                                         new SelectListItem() {Text="Tambahan", Value="Tambahan"},
                                                         new SelectListItem() {Text="Vocational", Value="Vocational"}},
                                                         new { @style = "height:25px;width:150px" })
        
         @Html.ValidationMessageFor(model => model.SubType)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namarina2/Views/Class/Delete.cshtml
@model Namarina2.Models.Class

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Class</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ClassCode)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ClassCode)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Namarina2/Views/Class/Details.cshtml
@model Namarina2.Models.Class

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>
<h3>@Html.DisplayFor(model => model.ClassCode)</h3>
<h4>Pengajar : @{if (Model.TeacherAssignments != null && Model.TeacherAssignments.Count > 0) { 
                     @Model.TeacherAssignments.First().Teacher.Name; 
                 }}</h4>

<p>
    @foreach(var e in (List<Namarina2.Models.Student>)@ViewBag.StudentInClass)
    {
        <div style="margin-bottom:4px">@e.Name    @Html.ActionLink("Ganti Kelas", "ChangeClass", "Student", new { @id = e.StudentID }, new {@style="color:blue" })</div> 
        
    }
    
</p>

<p>
    @Html.ActionLink("Edit Kelas", "Edit", new { id=Model.ClassID }) @if(!Request.IsAjaxRequest())
                                                               {
                                                                   @Html.Raw("|")    @Html.ActionLink("Back to List", "Index")
                                                               }
</p>

Namarina2/Views/Class/Edit.cshtml
@model Namarina2.Models.Class

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Class</legend>

        @Html.HiddenFor(model => model.ClassID)

        <div class="editor-label">
            @Html.LabelFor(model => model.ClassCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ClassCode)
            @Html.ValidationMessageFor(model => model.ClassCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namarina2/Views/Class/Index.cshtml
@model IEnumerable<Namarina2.Models.Class>

@{
    ViewBag.Title = "Index";
}
<input style="float: right; display: none; height: 25px" placeholder="Cari kelas" id="carikelas" />

<h2>Daftar Kelas</h2>

@if (User.IsInRole("manajer"))
{
    <p>
        @Html.ActionLink("Buat Kelas Baru", "Create")
    </p>
}
<p id="ajax-loader" style="text-align: center">
    preparing data..<br />
    <img src="~/Images/ajax-loader.gif" />
</p>

<div id="classes" style="display: none">
    <div id="tabstrip">
        <ul>
            <li class="k-state-active">Pusat
            </li>
            <li>Kebayoran
            </li>
        </ul>
        <div>
            <table>
                <tr>
                    <td>
                        <table id="grid-class-pusat">
                        </table>
                    </td>
                    <td>
                        <div style="margin-left: 20px" id="class-detail-pusat">
                        </div>
                        <div style="margin-left: 20px; display: none" id="ajax-loader2-pusat">
                            <img src="~/Images/ajax-loader.gif" />
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <div>
            <table>
                <tr>
                    <td>
                        <table id="grid-class-kebayoran">
                        </table>
                    </td>
                    <td>
                        <div style="margin-left: 20px" id="class-detail-kebayoran">
                        </div>
                        <div style="margin-left: 20px; display: none" id="ajax-loader2-kebayoran">
                            <img src="~/Images/ajax-loader.gif" />
                        </div>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
        var datasourcePusat = {};
        var datasourceKebayoran = {};
        var curBranch = "pusat";

        function onTabSelect(e) {
            $("#carikelas").val("");
            filterGrid();
            curBranch = $(e.item).find("> .k-link").text().toLowerCase();
        }

        function ViewClassDetail(e) {
            e.preventDefault();
            $("#class-detail-" + curBranch).hide();
            $("#ajax-loader2-" + curBranch).show();
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            $.ajax({
                type: "GET",
                cache: false,
                url: "@Url.Action("Details", "Class")",
                        data: { id: dataItem.ClassID },
                        success: function (data) {
                            $("#ajax-loader2-" + curBranch).hide();
                            $("#class-detail-" + curBranch).show();
                            $("#class-detail-" + curBranch).html(data);
                        }
                    });
                }

                $(document).ready(function () {
                    $("#tabstrip").kendoTabStrip({
                        select: onTabSelect,
                        animation: {
                            open: {
                                effects: "fadeIn"
                            }
                        }
                    });

                    $.ajax({
                        type: "GET",
                        cache: false,
                        url: "@Url.Action("GetClasses", "Class")" + "/?branch=pusat",
                success: function (data) {
                    datasourcePusat = data;
                    InitGrid("pusat");
                }
            });

            $.ajax({
                type: "GET",
                cache: false,
                url: "@Url.Action("GetClasses", "Class")" + "/?branch=kebayoran",
                success: function (data) {
                    datasourceKebayoran = data;
                    InitGrid("kebayoran");
                }
            });

            $("#carikelas").keyup(function () {
                filterGrid();
            });
                });

        function filterGrid() {
            $filter = new Array();

            $Name = $("#carikelas").val();

            if ($Name) {
                $filter.push({ field: "Name", operator: "contains", value: $Name });
            }

            var grid = $("#grid-class-" + curBranch).data("kendoGrid");
            grid.dataSource.filter($filter);
        }

        function InitGrid(branch) {

            $("#grid-class-" + branch).kendoGrid({
                dataSource: {
                    data: (branch == "pusat") ? datasourcePusat.classData : datasourceKebayoran.classData,
                    schema: {
                        model: {
                            fields: {
                                ClassCode: { type: "string" },
                                Name: { type: "string" },
                                StudentCount: { type: "number" }
                            }
                        }
                    },
                    pageSize: 10
                },
                dataBound: function (e) {
                    $('#ajax-loader').hide();
                    $('#classes').show();
                    $('#carikelas').show();
                },
                pageable: true,
                filterable: true,
                columns: [
                                {
                                    field: "ClassID",
                                    hidden: true
                                },
                                {
                                    field: "ClassCode",
                                    title: "Kode Kelas",
                                    width: 100
                                },
                                {
                                    field: "Name",
                                    title: "Nama Kelas",
                                    width: 200
                                },
                                {
                                    field: "StudentCount",
                                    title: "Jumlah Murid",
                                    width: 130,
                                    attributes: {
                                        "class": "center"
                                    }
                                },
                                {
                                    command: { text: "Lihat Murid", click: ViewClassDetail }, title: " ", width: "140px", attributes: {
                                        "class": "center"
                                    }
                                }
                ]
            });
        }
    </script>
}