Namarina2/Models/Guardian.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Namarina2.Models
{
    public class Guardian
    {
        public int GuardianID { get; set; }

        [MaxLength(100)]
        [Required]
        [DisplayName("Nama")]
        public string Name { get; set; }

        [MaxLength(20)]
        [Required]
        [DisplayName("Hubungan")]
        public string Relationship { get; set; }

        [MaxLength(50)]
        public string Email { get; set; }

        [MaxLength(50)]
        [DisplayName("No Telepon Rumah")]
        public string LandlinePhoneNumber { get; set; }

        [MaxLength(50)]
        [Required]
        [DisplayName("No HP")]
        public string MobilePhoneNumber { get; set; }

        [MaxLength(250)]
        [Required]
        [DisplayName("Alamat Rumah")]
        public string Address { get; set; }

        [MaxLength(50)]
        [DisplayName("Pekerjaan")]
        public string Job { get; set; }

        [MaxLength(200)]
        [DisplayName("Nama Kantor")]
        public string OfficeName { get; set; }

        [MaxLength(250)]
        [DisplayName("Alamat Kantor")]
        public string OfficeAddress { get; set; }

        [MaxLength(50)]
        [DisplayName("No Telp Kantor")]
        public string OfficePhone { get; set; }

        public int StudentID { get; set; }
        public virtual Student Student { get; set; }

        public bool IsMainGuardian { get; set; }
    }
}

Namarina2/Controllers/GuardianController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Namarina2.Models;
using Namarina2.DAL;
using Namarina2.Filters;

namespace Namarina2.Controllers
{
    [InitializeSimpleMembership]
    public class GuardianController : Controller
    {
        private NamarinaDbContext db = new NamarinaDbContext();

        //
        // GET: /Guardian/

        [Authorize]
        public ActionResult Index(int studentID)
        {
            ViewBag.StudentID = studentID;
            ViewBag.StudentName = db.Students.Find(studentID).Name;
            
            return View();
        }

        [Authorize]
        public JsonResult GetGuardians(int studentId)
        {
            return Json(new
            {
                guardianData = db.Guardians.Where(m=>m.Student.StudentID == studentId).Select(m => new
                {
                    GuardianId = m.GuardianID,
                    Name = m.Name,
                    Relationship = m.Relationship,
                    OfficeAddress = m.OfficeAddress,
                    MobilePhoneNo = m.MobilePhoneNumber,
                    Job = m.Job,
                    Email = m.Email
                }).ToList()
            }, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Guardian/Details/5
        [Authorize]
        public ActionResult Details(int id = 0)
        {
            Guardian guardian = db.Guardians.Find(id);
            if (guardian == null)
            {
                return HttpNotFound();
            }
            return View(guardian);
        }

        //
        // GET: /Guardian/Create
        [Authorize]
        public ActionResult Create(int studentID)
        {
            ViewBag.StudentID = studentID;
            return View();
        }

        //
        // POST: /Guardian/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(Guardian guardian)
        {
            if (ModelState.IsValid)
            {
                db.Guardians.Add(guardian);
                db.SaveChanges();
                return RedirectToAction("Index", new { @studentId = guardian.StudentID });
            }

            return View(guardian);
        }

        //
        // GET: /Guardian/Edit/5
        [Authorize]
        public ActionResult Edit(int id = 0)
        {
            Guardian guardian = db.Guardians.Find(id);
            if (guardian == null)
            {
                return HttpNotFound();
            }
            return View(guardian);
        }

        //
        // POST: /Guardian/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Guardian guardian)
        {
            if (ModelState.IsValid)
            {
                db.Entry(guardian).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { @studentId = guardian.StudentID });
            }
            return View(guardian);
        }

        //
        // GET: /Guardian/Delete/5
        [Authorize]
        public ActionResult Delete(int id = 0)
        {
            Guardian guardian = db.Guardians.Find(id);
            if (guardian == null)
            {
                return HttpNotFound();
            }
            return View(guardian);
        }

        //
        // POST: /Guardian/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            Guardian guardian = db.Guardians.Find(id);
            db.Guardians.Remove(guardian);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Namarina2/Views/Guardian/Create.cshtml
@model Namarina2.Models.Guardian

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guardian</legend>
        @Html.Hidden("StudentID", (int)ViewBag.StudentID)
        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Relationship)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Relationship, new List<SelectListItem>()
               {
                    new SelectListItem() {Text="Bapak", Value="Bapak"},
                   new SelectListItem() {Text="Ibu", Value="Ibu"},
                   new SelectListItem() {Text="Suami", Value="Suami"},
                   new SelectListItem() {Text="Kakek/Nenek", Value="Kakek/Nenek"},
                   new SelectListItem() {Text="Kakak/Adik", Value="Kakak/Adik"},
                   new SelectListItem() {Text="Saudara sepupu", Value="Saudara sepupu"},
                   new SelectListItem() {Text="Paman/Bibi", Value="Paman/Bibi"},
                   new SelectListItem() {Text="Lainnya", Value="Lainnya"}
               }, "-Pilih Hubungan-")
               @Html.ValidationMessageFor(model => model.Relationship)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LandlinePhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LandlinePhoneNumber)
            @Html.ValidationMessageFor(model => model.LandlinePhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MobilePhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MobilePhoneNumber)
            @Html.ValidationMessageFor(model => model.MobilePhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.OfficeName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficeName)
            @Html.ValidationMessageFor(model => model.OfficeName)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.OfficeAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficeAddress)
            @Html.ValidationMessageFor(model => model.OfficeAddress)
        </div>

         <div class="editor-label">
            @Html.LabelFor(model => model.OfficePhone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficePhone)
            @Html.ValidationMessageFor(model => model.OfficePhone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Job)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Job)
            @Html.ValidationMessageFor(model => model.Job)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { studentId = ViewBag.StudentID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namarina2/Views/Guardian/Delete.cshtml
@model Namarina2.Models.Guardian

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Guardian</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Relationship)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Relationship)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LandlinePhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LandlinePhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MobilePhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MobilePhoneNumber)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Job)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Job)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.IsMainGuardian)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsMainGuardian)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Namarina2/Views/Guardian/Details.cshtml
@model Namarina2.Models.Guardian

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Guardian</legend>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Relationship)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Relationship)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Email)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Email)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.LandlinePhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LandlinePhoneNumber)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.MobilePhoneNumber)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MobilePhoneNumber)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.Address)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Address)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.OfficeName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OfficeName)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.OfficeAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OfficeAddress)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.OfficePhone)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.OfficePhone)
    </div>
    <div class="display-label">
        @Html.DisplayNameFor(model => model.Job)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Job)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.IsMainGuardian)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.IsMainGuardian)
    </div>
</fieldset>
<p>
    
        @Html.ActionLink("Edit", "Edit", new { id=Model.GuardianID }) 
    @Html.ActionLink("Back to List", "Index", new { @studentId = Model.StudentID })
</p>

Namarina2/Views/Guardian/Edit.cshtml
@model Namarina2.Models.Guardian

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Guardian</legend>
        @Html.HiddenFor(model=>model.StudentID)
        @Html.HiddenFor(model => model.GuardianID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Relationship)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.Relationship, new List<SelectListItem>()
               {
                   new SelectListItem() {Text="Bapak", Value="Bapak"},
                   new SelectListItem() {Text="Ibu", Value="Ibu"},
                   new SelectListItem() {Text="Suami", Value="Suami"},
                   new SelectListItem() {Text="Kakek/Nenek", Value="Kakek/Nenek"},
                   new SelectListItem() {Text="Kakak/Adik", Value="Kakak/Adik"},
                   new SelectListItem() {Text="Saudara sepupu", Value="Saudara sepupu"},
                   new SelectListItem() {Text="Paman/Bibi", Value="Paman/Bibi"},
                   new SelectListItem() {Text="Lainnya", Value="Lainnya"}
               }, "-Pilih Hubungan-")
            @Html.ValidationMessageFor(model => model.Relationship)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Email)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Email)
            @Html.ValidationMessageFor(model => model.Email)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LandlinePhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LandlinePhoneNumber)
            @Html.ValidationMessageFor(model => model.LandlinePhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MobilePhoneNumber)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MobilePhoneNumber)
            @Html.ValidationMessageFor(model => model.MobilePhoneNumber)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Address)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Address)
            @Html.ValidationMessageFor(model => model.Address)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Job)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Job)
            @Html.ValidationMessageFor(model => model.Job)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OfficeName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficeName)
            @Html.ValidationMessageFor(model => model.OfficeName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OfficeAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficeAddress)
            @Html.ValidationMessageFor(model => model.OfficeAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.OfficePhone)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.OfficePhone)
            @Html.ValidationMessageFor(model => model.OfficePhone)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.IsMainGuardian)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.IsMainGuardian)
            @Html.ValidationMessageFor(model => model.IsMainGuardian)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { studentId = Model.StudentID })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Namarina2/Views/Guardian/Index.cshtml
@model IEnumerable<Namarina2.Models.Guardian>

@{
    ViewBag.Title = "Index";
}

<h2>Keluarga Murid - @ViewBag.StudentName</h2>

<p>
    @Html.ActionLink("Tambah data keluarga", "Create", new { @studentID = (int)ViewBag.StudentID})
</p>

@if(Convert.ToString(Request.QueryString["isRegistration"]) == "1")
{
    <div style="text-align: center">
    <ol class="round">
        <li class="one">&nbsp;&nbsp;&nbsp;&nbsp; Isi Biodata dan Kuesioner
        </li>

        <li class="two">&nbsp;&nbsp;&nbsp;&nbsp; Pilih kelas yang mau didaftar
        </li>

        <li class="three current">&nbsp;&nbsp;&nbsp;&nbsp; Lengkapi data keluarga
        </li>
    </ol>
</div>
<br />
}

<p id="ajax-loader" style="text-align:center">preparing data..<br />
<img src="~/Images/ajax-loader.gif" /></p>

<table id="grid-guardian" style="display:none">
</table>

@section scripts {
    <script type="text/javascript">

        var datasource = {};

        $(document).ready(function () {
            $.ajax({
                type: "GET",
                cache: false,
                url: "@Url.Action("GetGuardians", "Guardian")",
                data: {studentId : @ViewBag.StudentID},
                success: function (data) {
                    datasource = data;                   
                    InitGrid();
                }
            });           
        });

        function InitGrid() {
            $("#grid-guardian").kendoGrid({
                dataSource: {
                    data: datasource.guardianData,
                    pageSize: 10
                },
                dataBound: function (e) {
                    $('#ajax-loader').hide();
                    $('#grid-guardian').show();
                },               
                pageable: true,
                columns: [
                            {
                                field: "GuardianId",
                                hidden: true
                            },
                            {
                                field: "Name",
                                title: "Nama",
                                headerAttributes: {
                                    "class": "center",
                                }
                            },
                            {
                                field: "Relationship",
                                title: "Hubungan",
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }                               
                            },
                            {
                                field: "Email",
                                title: "Email",
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }
                            },
                            {
                                field: "MobilePhoneNo",
                                title: "No HP",
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }

                            },
                            {
                                field: "OfficeAddress",
                                title: "Alamat Kantor",                               
                                headerAttributes: {
                                    "class": "center",
                                }
                            },
                            {
                                field: "Job",
                                title: "Pekerjaan",
                                headerAttributes: {
                                    "class": "center",
                                },
                                attributes: {
                                    "class": "center"
                                }
                            },
                            {
                                command: [{ text: "Lihat Detail", click: showDetails }, { text: "Edit", click: edit}], title: " ", width: "140px", attributes: {
                                    "class": "center"
                                }
                            }
                ]            
            });           
        }

        function showDetails(e) {
            e.preventDefault();
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            location.href = "/Guardian/Details/" +dataItem.GuardianId;
        }

        function edit(e) {
            e.preventDefault(e);
            var dataItem = this.dataItem($(e.currentTarget).closest("tr"));
            location.href = "/Guardian/Edit/" +dataItem.GuardianId;
        }
        </script>
    }